main: me.irewiewer.silktouchhand.Main
name: SilkTouchHand
version: 0.4
description: Share the touch of the chosen ones.
author: iRewiewer
api-version: 1.18
commands:
    bless:
        usage: /bless <player>
        description: If you are one of the chosen ones, you may share your gift with others.
    unbless:
        usage: /unbless <Player>
        description: Remove blessing form <Player>
    blessed:
        usage: /blessed
        description: Check if you are part of the chosen ones.